### ISSUE TITLE
Segmentation Fault when a ROA advertise a subset that isn't included on parents resources

### ISSUE THREAD

**Issue by TheRedTrainer** [ydahhrk/rpki-validator#2]
When the rpki validator tries to validate a ROA that contains the ip resources 1-50.0.0.0/9 and its EE contains the resource 255.0.0.0/9, the following stack trace is displayed:

Segmentation Fault. Stack trace:
rpki_validator(print_stack_trace+0x32) [0x558df183feb2]
rpki_validator(+0x8f96) [0x558df183ff96]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7f868ae94890]
rpki_validator(+0x13600) [0x558df184a600]
rpki_validator(sarray_contains+0x53) [0x558df1842ea3]
rpki_validator(res4_contains_prefix+0x3e) [0x558df184a78e]
rpki_validator(handle_roa+0x54f) [0x558df18499af]
rpki_validator(rpp_traverse+0x112) [0x558df1842b82]
rpki_validator(certificate_traverse+0x2a9) [0x558df18486c9]
rpki_validator(+0x7c41) [0x558df183ec41]
rpki_validator(foreach_uri+0x4d) [0x558df184a09d]
rpki_validator(main+0xc2) [0x558df183ea12]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f868aab2b97]
rpki_validator(_start+0x2a) [0x558df183ea7a]
(Stack size was 14.)

**Comment by ydahhrk** [comment]
Fixed in 4e6458b4f307781c626464789e849a03fef6fd10.
